apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-to-k8s
spec:
  inputs:
    resources:
    - name: manifests
      type: git
    - name: builtImage
      type: image
    params:
    - name: tenantName
      description: The tenant name
      default: default
    - name: appName
      description: The APP name
    - name: appEnv
      description: The APP environment
  steps:
  - name: kustomize
    image: takitake/kustomize:v2.0.3
    command:
    - /bin/sh
    args:
    - -ce
    - |
      set -e
      set -x
      cd /workspace/manifests/tenants/${inputs.params.tenantName}/apps/${inputs.params.appName}/k8s/overlays/${inputs.params.appEnv}
      kustomize edit set image ${inputs.params.appName}=${inputs.resources.builtImage.url}
      kustomize build --output /workspace/manifest.yaml
  - name: kubectl-appy
    image: takitake/kubectl:v1.13.3
    command:
    -  kubectl
    args:
    - apply
    - --filename
    - /workspace/manifest.yaml
