apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: deploy
spec:
  params:
  - name: tenantName
  - name: appName
  - name: appEnv
  - name: version
  resources:
  - name: appSrc
    type: git
  - name: appImage
    type: image
  - name: manifests
    type: git
  tasks:
  - name: build-push-with-kaniko
    taskRef:
      name: build-push-with-kaniko
    resources:
      inputs:
      - name: appSrc
        resource: appSrc
      outputs:
      - name: builtImage
        resource: appImage
    params:
    - name: version
      value: "${params.version}"
  - name: deploy-to-k8s
    taskRef:
      name: deploy-to-k8s
    runAfter:
    - build-push-with-kaniko
    resources:
      inputs:
      - name: manifests
        resource: manifests
      - name: builtImage
        resource: appImage
        from: [build-push-with-kaniko]
    params:
    - name: tenantName
      value: "${params.tenantName}"
    - name: appName
      value: "${params.appName}"
    - name: appEnv
      value: "${params.appEnv}"
