apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-test
spec:
  type: git
  params:
  - name: url
    value: https://github.com/TakiTake/tekton-test.git
  - name: revision
    value: feature/pipeline
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: deploy-hello-world
spec:
  serviceAccount: deploy-bot
  taskRef:
    name: deploy-to-k8s
  trigger:
    type: manual
  inputs:
    resources:
    - name: manifests
      resourceRef:
        name: tekton-test
    params:
    - name: tenant
      value: default
    - name: app
      value: hello-world
    - name: env
      value: dev
