apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: hello-world-src
spec:
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: https://github.com/TakiTake/hello-world-go.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: hello-world-image
spec:
  type: image
  params:
  - name: url
    value: takitake/hello-world-go
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-test
spec:
  type: git
  params:
  - name: url
    value: https://github.com/TakiTake/tekton-test.git
  - name: revision
    value: master
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: deploy
spec:
  serviceAccount: deploy-bot
  pipelineRef:
    name: deploy
  params:
  - name: tenantName
    value: default
  - name: appName
    value: hello-world
  - name: appEnv
    value: dev
  - name: version
    value: '1.0.0'
  resources:
  - name: appSrc
    resourceRef:
      name: hello-world-src
  - name: appImage
    resourceRef:
      name: hello-world-image
  - name: manifests
    resourceRef:
      name: tekton-test
