apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-go
  name: hello-world-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-go
  template:
    metadata:
      labels:
        app: hello-world-go
    spec:
      containers:
      - image: takitake/hello-world-go
        name: hello-world-go
