apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: kubectl-src
spec:
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: https://github.com/TakiTake/dockerfiles.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: kubectl-image
spec:
  type: image
  params:
  - name: url
    value: takitake/kubectl
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: build-push-kubectl
spec:
  serviceAccount: deploy-bot
  taskRef:
    name: build-push-with-kaniko
  trigger:
    type: manual
  inputs:
    resources:
    - name: app
      resourceRef:
        name: kubectl-src
    params:
    - name: version
      value: '1.13.3'
    - name: pathToDockerFile
      value: /workspace/app/kubectl/Dockerfile
    - name: pathToContext
      value: /workspace/app/kubectl
  outputs:
    resources:
    - name: builtImage
      resourceRef:
        name: kubectl-image
