apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-test
spec:
  type: git
  params:
  - name: url
    value: https://github.com/TakiTake/tekton-test.git
  - name: revision
    value: master
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: deploy-nginx
spec:
  serviceAccount: deploy-bot
  taskRef:
    name: deploy-wo-building-to-k8s
  inputs:
    resources:
    - name: manifests
      resourceRef:
        name: tekton-test
    params:
    - name: tenantName
      value: default
    - name: appName
      value: nginx
    - name: appEnv
      value: dev
