apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: kustomize-src
spec:
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: https://github.com/TakiTake/dockerfiles.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: kustomize-image
spec:
  type: image
  params:
  - name: url
    value: takitake/kustomize
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: build-push-kustomize
spec:
  serviceAccount: deploy-bot
  taskRef:
    name: build-push-with-kaniko
  inputs:
    resources:
    - name: app
      resourceRef:
        name: kustomize-src
    params:
    - name: version
      value: '2.0.3'
    - name: pathToDockerFile
      value: /workspace/app/kustomize/Dockerfile
    - name: pathToContext
      value: /workspace/app/kustomize
  outputs:
    resources:
    - name: builtImage
      resourceRef:
        name: kustomize-image
